Compilation unit skeleton for job control; minor style changes. Updated formatting in README and added a little more information :cow:.

diff --git a/test b/test
--- a/test
+++ b/test
@@ -50,7 +50,7 @@ buildOutput () {
 }
 
 echo "Building µShell..."
-make shell
+make shell || fail "Build failed."
 
 echo "Running µShell end-to-end tests..."
 
